// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kikils/desk-squat-tracker/internal/domain/repository (interfaces: FaceRepository,JudgementRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_repository.go -package=repository . FaceRepository,JudgementRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"
	time "time"

	entity "github.com/kikils/desk-squat-tracker/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockFaceRepository is a mock of FaceRepository interface.
type MockFaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFaceRepositoryMockRecorder
	isgomock struct{}
}

// MockFaceRepositoryMockRecorder is the mock recorder for MockFaceRepository.
type MockFaceRepositoryMockRecorder struct {
	mock *MockFaceRepository
}

// NewMockFaceRepository creates a new mock instance.
func NewMockFaceRepository(ctrl *gomock.Controller) *MockFaceRepository {
	mock := &MockFaceRepository{ctrl: ctrl}
	mock.recorder = &MockFaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFaceRepository) EXPECT() *MockFaceRepositoryMockRecorder {
	return m.recorder
}

// Detect mocks base method.
func (m *MockFaceRepository) Detect(frame []byte, t time.Time) (*entity.Face, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detect", frame, t)
	ret0, _ := ret[0].(*entity.Face)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detect indicates an expected call of Detect.
func (mr *MockFaceRepositoryMockRecorder) Detect(frame, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detect", reflect.TypeOf((*MockFaceRepository)(nil).Detect), frame, t)
}

// MockJudgementRepository is a mock of JudgementRepository interface.
type MockJudgementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJudgementRepositoryMockRecorder
	isgomock struct{}
}

// MockJudgementRepositoryMockRecorder is the mock recorder for MockJudgementRepository.
type MockJudgementRepositoryMockRecorder struct {
	mock *MockJudgementRepository
}

// NewMockJudgementRepository creates a new mock instance.
func NewMockJudgementRepository(ctrl *gomock.Controller) *MockJudgementRepository {
	mock := &MockJudgementRepository{ctrl: ctrl}
	mock.recorder = &MockJudgementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJudgementRepository) EXPECT() *MockJudgementRepositoryMockRecorder {
	return m.recorder
}

// GetLast mocks base method.
func (m *MockJudgementRepository) GetLast() (*entity.Judgement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLast")
	ret0, _ := ret[0].(*entity.Judgement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLast indicates an expected call of GetLast.
func (mr *MockJudgementRepositoryMockRecorder) GetLast() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLast", reflect.TypeOf((*MockJudgementRepository)(nil).GetLast))
}

// Save mocks base method.
func (m *MockJudgementRepository) Save(judgement *entity.Judgement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", judgement)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockJudgementRepositoryMockRecorder) Save(judgement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockJudgementRepository)(nil).Save), judgement)
}
