// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FaceViewModel はフロント用の顔検出表示モデル。app 層で定義する。
 */
export class FaceViewModel {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "frameWidth": number;
    "frameHeight": number;
    "ratio": number;
    "state": string;
    "repCompleted": boolean;

    /** Creates a new FaceViewModel instance. */
    constructor($$source: Partial<FaceViewModel> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("frameWidth" in $$source)) {
            this["frameWidth"] = 0;
        }
        if (!("frameHeight" in $$source)) {
            this["frameHeight"] = 0;
        }
        if (!("ratio" in $$source)) {
            this["ratio"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("repCompleted" in $$source)) {
            this["repCompleted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FaceViewModel instance from a string or object.
     */
    static createFrom($$source: any = {}): FaceViewModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FaceViewModel($$parsedSource as Partial<FaceViewModel>);
    }
}
