// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GetSettingOutput {
    "TopRatio": number;
    "BottomRatio": number;

    /** Creates a new GetSettingOutput instance. */
    constructor($$source: Partial<GetSettingOutput> = {}) {
        if (!("TopRatio" in $$source)) {
            this["TopRatio"] = 0;
        }
        if (!("BottomRatio" in $$source)) {
            this["BottomRatio"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetSettingOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetSettingOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetSettingOutput($$parsedSource as Partial<GetSettingOutput>);
    }
}

export class GetStatsOutput {
    "RepCount": number;

    /** Creates a new GetStatsOutput instance. */
    constructor($$source: Partial<GetStatsOutput> = {}) {
        if (!("RepCount" in $$source)) {
            this["RepCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetStatsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetStatsOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetStatsOutput($$parsedSource as Partial<GetStatsOutput>);
    }
}
