// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Quit はアプリ全体を終了します（トレイ常駐も含めてプロセスが終了します）。
 * バインディングの応答が WebView に返る前に同期で Quit するとデッドロックするため、
 * メインスレッドへ非同期で渡してから終了処理を走らせます。
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2343774452);
}
