// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CameraDevice はフロントに渡すカメラ情報。
 */
export class CameraDevice {
    "Index": number;
    "Name": string;

    /** Creates a new CameraDevice instance. */
    constructor($$source: Partial<CameraDevice> = {}) {
        if (!("Index" in $$source)) {
            this["Index"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CameraDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): CameraDevice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CameraDevice($$parsedSource as Partial<CameraDevice>);
    }
}
