// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usecase$0 from "../../../usecase/models.js";

export function GetSetting(): $CancellablePromise<usecase$0.GetSettingOutput | null> {
    return $Call.ByID(2200741943).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateSetting(topRatio: number, bottomRatio: number): $CancellablePromise<void> {
    return $Call.ByID(3724466834, topRatio, bottomRatio);
}

// Private type creation functions
const $$createType0 = usecase$0.GetSettingOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
