// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usecase$0 from "../../../usecase/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export function GetStats(t: time$0.Time): $CancellablePromise<usecase$0.GetStatsOutput | null> {
    return $Call.ByID(722399708, t).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = usecase$0.GetStatsOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
